name = "PaperMod-somni"
license = "MIT"
licenselink = "https://github.com/somnisomni/somni.log/blob/main/theme/LICENSE"
description = "A fast, clean, responsive Hugo theme customized for somni.log"
homepage = "https://github.com/somnisomni/somni.log/tree/main/theme"
demosite = "https://log.somni.one"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.146.0"

[author]
  name = "somni"
  homepage = "https://somni.one"

# If porting an existing theme
[original]
  name = "PaperMod"
  author = "Aditya Telange"
  homepage = "https://github.com/adityatelange/"
  repo = "https://github.com/adityatelange/hugo-PaperMod"
